[project]
name = "browser-agent"
version = "0.1.0"
description = "基于LangGraph的工作流Agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-core>=0.1.0",
    "langchain-openai>=0.1.0",
    "langgraph>=0.3.27",
    "typing-extensions>=4.5.0",
]
